### ISSUE TITLE
Graphite Prefix

### ISSUE THREAD

**Issue by jeffpeacock** [nctiggy/VMAX-Graphite#10]
Prepend data sent to hosted graphite with a prefix to support API key + folder structure.

example: <apikey>.<fgid>.symmetrix.serial

**Comment by nctiggy** [comment]
Think I finished this up. Currently pushed to the dev branch. Can you try it out?

**Comment by jeffpeacock** [comment]
I need to get ruby installed on our prod boxes, they’re currently only running collectd. Once I get that set I’ll run some tests and see if we run into the same problem with data collection that we had before. We’re noticing large data gaps on collectd gathering info from our switches, even with the interval set to 300.

With your other customer, are they having any similar issues, or can they successfully gather all metrics from your script?

**Comment by nctiggy** [comment]
Any chance at testing this? I have now released to the master branch as this appears to work for other customers now.

**Comment by jeffpeacock** [comment]
I was able to test it briefly. However it didn’t pull the Array stats, I don’t recall offhand if I had set them to off. I I’ll try to test the master either tomorrow or Monday. I’ve been in Azure training all week.
