### ISSUE TITLE
collector.rb:66:in `get_array_metrics': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by yesoos** [nctiggy/VMAX-Graphite#7]
Trying to get your collector working, and I get following error:

./collector.rb:66:in `get_array_metrics': undefined method`[]' for nil:NilClass (NoMethodError)
        from ./collector.rb:133:in `block (4 levels) in <main>'
        from ./collector.rb:131:in`each'
        from ./collector.rb:131:in `block (3 levels) in <main>'
        from ./collector.rb:126:in`each'
        from ./collector.rb:126:in `block (2 levels) in <main>'
        from ./collector.rb:125:in`each'
        from ./collector.rb:125:in `block in <main>'
        from ./collector.rb:122:in`each'
        from ./collector.rb:122:in `<main>'

**Comment by nctiggy** [comment]
Hey, yeah the master branch is unstable, I know that is backwards. The ucg branch is more functional but may actually work for array stats and most component stats.

**Comment by yesoos** [comment]
For UCG branch I get following issue:

/usr/local/rvm/gems/ruby-2.2.1/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!': 405 Method Not Allowed (RestClient::MethodNotAllowed)
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in`process_result'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:853:in`start'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in`execute'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
        from ./collector.rb:79:in`rest_post'
        from ./collector.rb:37:in `get_keys'
        from ./collector.rb:129:in`block (3 levels) in <main>'
        from ./collector.rb:126:in `each'
        from ./collector.rb:126:in`block (2 levels) in <main>'
        from ./collector.rb:125:in `each'
        from ./collector.rb:125:in`block in <main>'
        from ./collector.rb:122:in `each'
        from ./collector.rb:122:in`<main>'

**Comment by nctiggy** [comment]
That is actually making the rest call now, which is a good thing. As a starting point can you post your settings.json file?

**Comment by yesoos** [comment]
{
        "graphite": {
                "enabled": true,
                "host": "localhost",
                "port": "2003"
        },
        "csv": {
                "enabled": true
        },
        "unisphere": [
                {
                        "ip": "host",
                        "user": "smc",
                        "password": "pass",
                        "port": 8443,
                        "version": 7,
                        "symmetrix": [
                                { "sid": "sid1" },
                                { "sid": "sid2" }
                        ]
                }
        ],
        "monitor": [
                {
                        "scope": "Array",
                        "type": "performance"
                },
                {
                        "scope": "BEDirector",
                        "type": "performance"
                },
                {
                        "scope": "FEDirector",
                        "type": "performance"
                }
        ]
}

**Comment by nctiggy** [comment]
That looks good. Let's simplify. Remove one of the vmax's and also remove fe and be director. Also need to remove the trailing comma on the Sid and after scope.

**Comment by yesoos** [comment]
Did that - same issue.

**Comment by nctiggy** [comment]
Can you email me directly?

**Comment by nctiggy** [comment]
This looks like a malformed payload. Lets troubleshoot tomorrow to remedy the payload structure.

**Comment by nctiggy** [comment]
Fixes pushed to Master. These were syntax errors
