### ISSUE TITLE
Collection Interval

### ISSUE THREAD

**Issue by biancalana** [nctiggy/VMAX-Graphite#8]
It's not exactly one issue but a question... have you found a way to fetch metrics at a interval lower than 5 min ? I've had made a collector but aborted because 5 min interval for metrics is almost useless for me.

**Comment by nctiggy** [comment]
I'm checking for you. I'll reply when I have an answer

**Comment by nctiggy** [comment]
Sorry on the delay here. General rule of thumb here is that any thing less than 5 minutes (If you could make the change) could impact the array's ability to do it's primary function (Data integrity/response time/etc ;) ). I could not get validation on wether Unisphere could get lower than 5 minutes but TTP's can certainly collect at a more granular interval, again at the risk of slowing the box down.

Can I ask why 5 minute intervals is not useful?

**Comment by nctiggy** [comment]
Closing for now
